#!/usr/bin/python
print("张三，你好，欢迎来到Python世界")
print()
print()
print()
print("黄焱鑫，男，22，河南大学，软件工程")
print()
print()
print()
print()
print()
print("       英雄商城登录界面")
print("~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*")
print("        1.注册用户")
print("        2.用户登录")
print("        3.退出系统")
print("~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*")
print("（温馨提示）请输入您的选项：")

